env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
