requires:
- category: "development"
  name: "mocaccino-overlay-x"
  version: ">=0"
unpack: true
steps:
- USE=-harfbuzz emerge media-libs/freetype
- emerge dev-perl/XML-parser
- emerge -uDNv --with-bdeps=y --backtrack=100 --autounmask-keep-masks=y @world
- perl-cleaner --all
