env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
requires:
- category: "layers"
  name: "X"
  version: ">=0"
- category: "layers"
  name: "desktop-common"
  version: ">=0"
